#
# Don't use the playbook directly
#
# Required variables (play-scoped)
# - host_role
# - see also vars section

- hosts: "role-{{ host_role }}"
  gather_facts: no
  vars:
    appliance_user: "{{ host_role }}"
    appliance_dir: "{{ appliance_base_dir | default('/') }}{{ host_role }}"
    appliance_source_compose_path: "docker-compose/{{ host_role }}"
    appliance_compose_files:
      - docker-compose.yml
    appliance_compose_files_filtered: "{{ appliance_compose_files | default([]) | select() | map('trim') | list }}"

  tasks:
  - name: Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:

  - name: "Create user for {{ appliance_user }}"
    user:
      name: "{{ appliance_user }}"
      shell: /bin/bash
      home: "{{ appliance_dir }}"
      state: present
      groups: docker
      append: true

  - name: "Deploy docker-compose file for {{ host_role }}"
    template:
      src: "{{ appliance_source_compose_path }}/{{ item }}"
      dest: "{{ appliance_dir }}/{{ item }}"
      owner: root
      mode: 0644
    loop: "{{ appliance_compose_files_filtered }}"

  - name: "Create startup file for local use of {{ host_role }}"
    template:
      src: "templates/start-local.sh.j2"
      dest: "{{ appliance_dir }}/start-local.sh"
      owner: root
      mode: 0755

#  - name: "Start compose services for {{ host_role }}"
#    command: docker-compose up -d
#    args:
#      chdir: "{{ appliance_dir }}"
#    become: yes
#    become_user: "{{ appliance_user }}"
