- import_playbook: _appliance.yml
  vars:
    host_role: role_monitoring   
    appliance_name: prometheus
    appliance_user_id: 473
    appliance_autostart: "{{ prometheus_autostart | default(false) }}"
    appliance_swarm: "{{ swarm_mode | default(false) }}"
    appliance_auth: "{{ dashboards_auth }}"
    appliance_additional_dirs:
      - etc
      - data
    appliance_additional_files:
      etc/prometheus.yml: "{%- if swarm_mode | default(false) -%} etc/prometheus.swarm.yml {%- else -%} etc/prometheus.local.{{ balancer_type}}.yml {%- endif %}"
