- import_playbook: _appliance.yml
  vars:
    host_role: role_traefik   
    appliance_name: traefik
    appliance_autostart: "{{ traefik_autostart | default(true) }}"
    appliance_swarm: "{{ swarm_mode | default(false) }}"
    appliance_compose_files:
      - "{% if traefik_whoami | bool %} docker-compose.whoami.yml {% endif %}"
