- import_playbook: _appliance.yml
  vars:
    host_role: role_docker_system
    appliance_name: docker_system
    appliance_autostart: "{{ docker_system_autostart | default(true) }}"
    appliance_swarm: "{{ swarm_mode | default(false) }}"
