- import_playbook: _appliance.yml
  vars:
    host_role: role_traefik   
    appliance_name: traefik
    appliance_user_id: 470
    appliance_autostart: "{{ traefik_autostart | default(true) }}"
    appliance_swarm: "{{ swarm_mode | default(false) }}"
    appliance_compose_files:
      - "{% if traefik_whoami | bool %} docker-compose.whoami.yml {% endif %}"
      - "{% if logging_type | default(false) %} docker-compose.endpoint.{{ logging_type }}.yml {% endif %}"
    appliance_auth: "{{ dashboards_auth }}"
    # appliance_logging: "{{ logging_type }}"  # appliance_logging not supported in automatic mode
    appliance_environment: "{{ traefik_env }}"
