- import_playbook: _appliance.yml
  vars:
    host_role: role_webapp   
    appliance_name: webapp
    appliance_user_id: 789  # default grafana user in upstream
    appliance_autostart: "{{ webapp_autostart | default(false) }}"
    appliance_swarm: "{{ swarm_mode | default(false) }}"
    appliance_additional_files:
      env: env
