- import_playbook: _appliance.yml
  vars:
    host_role: role_metrics   
    appliance_name: metrics
    appliance_autostart: "{{ metrics_autostart | default(true) }}"
    appliance_swarm: "{{ swarm_mode | default(false) }}"
    appliance_logging: "{{ logging_type | default(false) }}"
