- hosts: all
  gather_facts: no

  tasks:
  - name: Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:

  - name: Install setfacl tool (used for ansible become invocation)
    apt:
      name: acl
      state: present

  - name: Add Docker apt signing key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker apt repository
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu bionic stable" ###FIXME codename
      state: present

  - name: Purge old docker-compose package
    apt:
      name: docker-compose
      state: absent

  - name: Install docker
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      state: present

  - name: Install dockerized docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/run.sh  ###FIXME version
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Put Docker daemon config in place (rotate docker logs)
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      owner: root
      mode: 0644
    notify:
      - Restart Docker daemon

  - name: Create group for running docker
    group:
      name: docker
      state: present
      system: true

  - name: Manage ubuntu user
    user:
      name: ubuntu
      state: present
      groups: docker
      append: true

  handlers:
  - name: Restart Docker daemon
    command: "systemctl restart docker"
