- hosts: localhost
  gather_facts: no
  vars:
    install_dir: /install
    appliance_name: "{{ lookup('env', 'APPLIANCE_NAME') | default('installer', True) }}"
    appliance_dir: "{{ install_dir }}/{{ lookup('env', 'APPLIANCE_DIR') | default(appliance_name, True) }}"
    docker_mode: "{{ lookup('env', 'DOCKER_MODE') | default('local', True) }}"
    balancer_type: "{{ lookup('env', 'BALANCER_TYPE') | default('caddy', True) }}"

  tasks:
  - name: "Deploy example postgres_config"
    copy:
      src: postgres_config
      dest: "{{ appliance_dir }}/postgres_config"
      force: no		# prevent overwriting if exists
      owner: root
      mode: 0600
