version: '3.6'

services:
  pgbackrest-exporter:
    image: erthad/pgbackrest_exporter
    restart: always
    ports:
    - "9854:9854"
    volumes:
    - /etc/pgbackrest/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro
    env_file:
     - pgbackrest_config

networks:
  default:
    external: true
    name: appliances
