version: '3.6'

services:
  seq:
    image: datalust/seq:2021.3
    user: "474"
    volumes:
      - ./data:/data
    restart: always

    environment:
      ACCEPT_EULA: Y

    labels: &seq-labels
      traefik.enable: "true"
      traefik.http.routers.seq.rule: "PathPrefix(`/`)"
      traefik.http.routers.seq.entrypoints: seq

  seq-input-gelf:
    image: datalust/seq-input-gelf
    user: "474"
    restart: always

    environment:
      SEQ_ADDRESS: http://seq:5341
    labels:
      logspout.exclude: 'true'

  logspout-gelf:
    image: erthad/logspout-gelf-tls
    user: "474:998"  # make sure 998 is your docker user group
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: gelf://seq-input-gelf:12201
    restart: always
    environment:
      EXCLUDE_LABEL: logspout.exclude
    labels:
      logspout.exclude: 'true'
