version: '3.6'

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    user: "473"
    volumes:
      - ./etc/:/etc/prometheus/
      - ./data:/prometheus_data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=/prometheus'
    restart: always

    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "PathPrefix(`/prometheus`)"
      traefik.http.routers.prometheus.entrypoints: dashboard
