version: '3.6'

services:
  prometheus:
    image: prom/prometheus:v2.31.1
    user: "473:999"
    volumes:
      - ./etc/:/etc/prometheus/
      - ./data:/prometheus_data
      - /var/run/docker.sock:/var/run/docker.sock:ro  # for service discovery to work ###FIXME disable for non-swarm setup ???
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=/prometheus'
    restart: always

    labels: &prometheus-labels
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "PathPrefix(`/prometheus`)"
      traefik.http.routers.prometheus.entrypoints: dashboard
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"  # required for swarm mode

    deploy:
      placement:
        constraints:
          - "node.role==manager"   # we don't support deploying stateful apps anywhere but on manager node
                                   ###FIXME: multi-manager setup is untested and might break
      labels:
        <<: *prometheus-labels
