version: '3'

services:
  whoami:
    image: "traefik/whoami"
    labels: &whoami-labels
      traefik.enable: "true"
      traefik.http.routers.whoami.rule: "(PathPrefix(`/whoami`))"
      traefik.http.routers.whoami.entrypoints: dashboard
      traefik.http.services.whoami.loadbalancer.server.port: "80"  # required for swarm mode
    deploy:
      labels:
        <<: *whoami-labels
