version: '3.6'

services:
  grafana:
    image: grafana/grafana
    user: "472"  # default grafana user in upstream
    volumes:
      - ./data:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
    environment:
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      GF_USERS_ALLOW_SIGN_UP: "false"
    env_file:
      - ./config.monitoring
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: "PathPrefix(`/grafana`)"
      traefik.http.routers.grafana.entrypoints: dashboard

###FIXME: consider putting that into standalone docker-compose file
networks:
  default:
    external: true
    name: traefik_network
