version: '3.6'

services:
  restic:
    image: erthad/restic-exporter
    command: /bin/false
    restart: "no"
    hostname: "${HOSTNAME}"
    env_file:
     - restic_config
    volumes:
     - /app:/data:ro
     - ../metrics-stats:/stats:rw
     - ./restic-exporter.yaml:/stats/restic-exporter.yaml:ro
