#
# Using filename of install-15.yml prevents creation of start.sh and stop.sh
#

- hosts: localhost
  gather_facts: no
  vars:
    install_dir: /install
    appliance_name: "{{ lookup('env', 'APPLIANCE_NAME') | default('installer', True) }}"
    appliance_dir: "{{ install_dir }}/{{ lookup('env', 'APPLIANCE_DIR') | default(appliance_name, True) }}"

  tasks:
  - name: "Create management scripts for {{ appliance_name }}"
    template:
      src: "{{ item }}"
      dest: "{{ appliance_dir }}/{{ item }}"
      owner: root
      mode: 0755
    with_items:
    - restic-run.sh

  - name: "Deploy example scripts"
    copy:
      src: "{{ item }}"
      dest: "{{ appliance_dir }}/{{ item }}"
      force: no		# prevent overwriting if exists
      owner: root
      mode: 0644
    with_items:
    - restic-exporter.yaml
    - restic.cron

  - name: "Deploy example config"
    copy:
      src: restic_config.example
      dest: "{{ appliance_dir }}/restic_config"
      force: no		# prevent overwriting if exists
      owner: root
      mode: 0644
