global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
         - targets: ['prometheus:9090']

  - job_name: 'traefik'
    scrape_interval: 5s
    static_configs:
         - targets: ['traefik:8080']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
         - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
         - targets: ['node-exporter:9100']
