version: '3.6'

services:
  webapp:
    image: 10.0.2.2:5000/http-pong ###FIXME
    restart: always

    configs:
     - source: webapp
       target: /app/.env
    env_file:
     - env

    labels: &webapp-labels
      traefik.enable: "true"
      traefik.http.routers.webapp.rule: "(PathPrefix(`/`))"
      traefik.http.routers.webapp.entrypoints: http
      traefik.http.services.webapp.loadbalancer.server.port: "5000"  ###FIXME required for swarm mode
    deploy:
      labels:
        <<: *webapp-labels

configs:
  webapp:
    file: ./env
