version: '3.6'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    command: -logtostderr -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    labels: &cadvisor-labels
      traefik.enable: "false"
      prometheus-job: cadvisor
    deploy:
      mode: global
      labels:
        <<: *cadvisor-labels

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    restart: always
    labels: &node-exporter-labels
      traefik.enable: "false"
      prometheus-job: node-exporter
    deploy:
      mode: global
      labels:
        <<: *node-exporter-labels

networks:
  default:
    external: true
    name: appliances
